package num;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NAT.java
//  @ Date : 2017-05-16
//  @ Author : 
//
//


public class NAT extends NUM {
	@Override
	public void setValue(int value) {
		if(value > 0){
			this.value = value;
		}
		else{
			System.exit(-1);
		}
	}
	
	NAT() {
		setValue(1);
	}
	
	NAT(int value) {
		setValue(value);
	}
	
	public void add(int value) {
		if(checkPositive(value) == true){
			this.value += value;
		}
		else{
			System.exit(-1);
		}
	}
	
	public void sub(int value) {
		if(checkPositive(value) == true){
			if(checkPositive(this.value - value) == true){
				this.value -= value;
			}
			else{
				System.exit(-1);
			}
		}
		else{
			System.exit(-1);
		}
	}
	
	public void multiple(int value) {
		if(checkPositive(value) == true){
			this.value *= value;
		}
		else{
			System.exit(-1);
		}
	}
	
	public boolean checkPositive(int value) {
		if(value > 0) return true;
		else return false;
	
	}
	
	public static void main(String[] args) {
		NAT nat = new NAT(5);
		System.out.println(nat.getValue());
		INT inte = new INT(-5);
		System.out.println(inte.getValue());
		nat.sub(4);
		System.out.println(nat.getValue());
	}


}
