package num;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NUM.java
//  @ Date : 2017-05-16
//  @ Author : 
//
//




public abstract class NUM {
	protected int value;
	public int getValue() {
		return this.value;
	}
	
	public abstract void setValue(int value);
}
