package nat;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : INT.java
//  @ Date : 2017-05-16
//  @ Author : 
//
//




public class INT {
	private int value;

	INT() {
	    setValue(0);
	}

	INT(int value) {
		this.value = value;
	}

	public int getValue() {
		return this.value;
	}
	
	public void setValue(int value) {
		this.value = value;
	}
	

	
	public void add(int value) {
		this.value += value;
	}
	
	public void sub(int value) {
		this.value -= value;
	}
	
	public void multiple(int value) {
		this.value *= value;
	}
}
