package nat;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : NAT.java
//  @ Date : 2017-05-16
//  @ Author : 
//
//




public class NAT extends INT{
	private int value;

	public void setVaule(int value) {
		if(checkPositive(value) == true) {
			this.value = value;
			System.out.println(this.value);
		}else{
			System.exit(-1);
		}
	}

	NAT() {
		setVaule(1);
	}

	NAT(int value) {
		setVaule(value);
	}
	
	public void add(int value) {
		if(checkPositive(value) == true) {
			this.value += value;
		}else{
			System.exit(-1);
		}
	}
	
	public void sub(int value) {
		if(checkPositive(value) == true) {
			if(checkPositive(this.value - value)){
				this.value -= value;
			}
			else{
				System.exit(-1);
			}
		}else{
			System.exit(-1);
		}
	}
	
	public void multiple(int value) {
		if(checkPositive(value) == true) {
			this.value *= value;
		}else{
			System.exit(-1);
		}
	}
	
	public boolean checkPositive(int value) {
		if(value > 0) return true;
		else return false;
	}
	
	public static void main(String[] args) {

		NAT nat = new NAT();
		System.out.println(nat.getValue());
		//NAT a = new NAT(-1);

		nat.setVaule(5);
		System.out.println(nat.getValue());
		nat.add(1);
		//System.out.println(nat);
		nat.sub(-7);
		//System.out.println(nat);
		nat.multiple(4);
		//System.out.println(nat);
	}
}
