//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : INT.java
//  @ Date : 2017-05-15
//  @ Author :
//
//



public class INT {
    private int value;

    public int getValue() {
        return value;
    }

    public void setValue(int value) {
        this.value = value;
    }

    INT() {
        this(0);
    }

    INT(int value) {
        this.value = value;
    }

    public void add(int value) {
        this.value += value;
    }

    public void sub(int value) {
        this.value -= value;
    }

    public void multiply(int value) {
        this.value *= value;
    }

    public static void main(String[] args) {
        INT a = new INT();
        System.out.println(a.getValue());
        a.setValue(5);
        System.out.println(a.getValue());
        a.add(2);
        System.out.println(a.getValue());
        a.sub(3);
        System.out.println(a.getValue());
        a.multiply(4);
        System.out.println(a.getValue());
    }
}
